spring:
  boot:
    admin:
      url: http://springbootadmin:8188
      client:
        prefer-ip: true
        
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://admin:admin123@registry:8761/eureka/
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
