spring:
  boot:
    admin:
      client:
        enable: false
        prefer-ip: true
        
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://admin:admin123@registry:8761/eureka/
management:
  context-path: /admin
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: '*'
