spring:
  boot:
    admin:
      url: http://springbootadmin:8188
      client:
        prefer-ip: true
        
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
